# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('birthday', models.DateField(verbose_name='your birthday')),
                ('gender', models.BooleanField(default=True, verbose_name='boy?')),
            ],
        ),
    ]
